micronaut.application.name=osmtilecache

# environment variables needed
# mandatory
temp.dir=${OSMTC_TEMP_DIR:./tmp}
# must NOT end with /
temp.dir.log=${OSMTC_TEMP_DIR:./tmp}/logs
osm.tiles.dir=${OSMTC_TILES_DIR:./tiles}
# optional
micronaut.server.port=${OSMTC_HTTP_PORT:8888}
micronaut.server.ssl.port=${OSMTC_HTTPS_PORT:4448}
# end environment variables needed

osm.endpoint.format=https://${OSMTC_TILE_SERVER:tile.openstreetmap.org}/%s/%s/%s.png
osm.refresh.tile.days=60
osm.config=${OSMTC_CONFIG:proxycache}
osm.precache.queue.size=100

micronaut.serde.serialization.inclusion=ALWAYS

threads.count=2
micronaut.executors.io.fixed.n-threads=2

datasources.default.password=
datasources.default.username=sa
datasources.default.url=jdbc:sqlite:${OSMTC_DB_DIR:./db}/data
datasources.default.driver-class-name=org.sqlite.JDBC
datasources.default.dialect=H2
datasources.default.hikari.maximum-pool-size=1
datasources.default.hikari.minimum-idle=0
micronaut.data.jdbc.connection.read-only=false
liquibase.datasources.default.change-log=classpath\:db/liquibase-changelog.xml
