micronaut.application.name=osmtilecache

# environment variables needed
# mandatory
temp.dir=${OSMTC_TEMP_DIR:/osmtilecache/tmp}
# must NOT end with /
temp.dir.log=${OSMTC_TEMP_DIR:/osmtilecache/tmp}/logs
# optional
micronaut.server.port=${OSMTC_HTTP_PORT:8888}
micronaut.server.ssl.port=${OSMTC_HTTPS_PORT:4448}
# end environment variables needed

osm.endpoint.format=https://tile.openstreetmap.org/%s/%s/%s.png
osm.refresh.tile.days=60
osm.config=${OSMTC_CONFIG:proxycache}
osm.precache.queue.size=100

micronaut.serde.serialization.inclusion=ALWAYS

threads.count=2
micronaut.security.authentication=session
micronaut.security.redirect.login-success=/
micronaut.security.redirect.login-failure=/authFailed
micronaut.server.cors.enabled=true
micronaut.executors.io.fixed.n-threads=2
